// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.CognitiveServices.FormRecognizer
{
    using Models;
    using System.Net;
    using System.Threading;
    using System.Threading.Tasks;
    using System.Text.RegularExpressions;
    using System;
    using System.IO;

    /// <summary>
    /// Extension methods for FormRecognizerClient.
    /// </summary>
    public static partial class FormRecognizerClientExtensions
    {


        public static async Task<AnalyzeOperationResult> AnalyzeLayoutAsync(this IFormRecognizerClient operations, string language, Uri uri, int retryTimes = 5, CancellationToken cancellationToken = default(CancellationToken))
        {
            using (var _result = await operations.AnalyzeLayoutWithHttpMessagesAsync(language, uri, null, cancellationToken).ConfigureAwait(false))
            {
                var header = _result.Headers;
                var guid = GetGuid(header.OperationLocation);
                return await operations.PollingResultAsync(guid, AnalyzeType.Layout, retryTimes, cancellationToken);
            }
        }

        public static async Task<AnalyzeOperationResult> AnalyzeLayoutAsync(this IFormRecognizerClient operations, string language, Stream fileStream, int retryTimes = 5, CancellationToken cancellationToken = default(CancellationToken))
        {
            using (var _result = await operations.AnalyzeLayoutWithHttpMessagesAsync(language, fileStream, null, cancellationToken).ConfigureAwait(false))
            {
                var header = _result.Headers;
                var guid = GetGuid(header.OperationLocation);
                return await operations.PollingResultAsync(guid, AnalyzeType.Layout, retryTimes, cancellationToken);
            }
        }

        public static async Task<AnalyzeOperationResult> AnalyzeLayoutAsync(this IFormRecognizerClient operations, string language, byte[] byteArray, int retryTimes = 5, CancellationToken cancellationToken = default(CancellationToken))
        {
            using (var _result = await operations.AnalyzeLayoutWithHttpMessagesAsync(language, byteArray, null, cancellationToken).ConfigureAwait(false))
            {
                var header = _result.Headers;
                var guid = GetGuid(header.OperationLocation);
                return await operations.PollingResultAsync(guid, AnalyzeType.Layout, retryTimes, cancellationToken);
            }
        }

        /// <summary>
        /// Get Analyze Layout Result
        /// </summary>
        /// <remarks>
        /// Track the progress and obtain the result of the analyze layout operation
        /// </remarks>
        /// <param name='operations'>
        /// The operations group for this extension method.
        /// </param>
        /// <param name='resultId'>
        /// Analyze operation result identifier.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        public static async Task<AnalyzeOperationResult> GetAnalyzeLayoutResultAsync(this IFormRecognizerClient operations, System.Guid resultId, CancellationToken cancellationToken = default(CancellationToken))
        {
            using (var _result = await operations.GetAnalyzeLayoutResultWithHttpMessagesAsync(resultId, null, cancellationToken).ConfigureAwait(false))
            {
                return _result.Body;
            }
        }

    }
}
