// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.CognitiveServices.FormRecognizer.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Serialization;
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Recognized field value.
    /// </summary>
    public partial class FieldValue
    {
        /// <summary>
        /// Initializes a new instance of the FieldValue class.
        /// </summary>
        public FieldValue()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FieldValue class.
        /// </summary>
        /// <param name="type">Type of field value. Possible values include:
        /// 'string', 'date', 'time', 'phoneNumber', 'number', 'integer',
        /// 'array', 'object'</param>
        /// <param name="valueString">String value.</param>
        /// <param name="valueDate">Date value.</param>
        /// <param name="valueTime">Time value.</param>
        /// <param name="valuePhoneNumber">Phone number value.</param>
        /// <param name="valueNumber">Floating point value.</param>
        /// <param name="valueInteger">Integer value.</param>
        /// <param name="valueArray">Array of field values.</param>
        /// <param name="valueObject">Dictionary of named field values.</param>
        /// <param name="text">Text content of the extracted field.</param>
        /// <param name="boundingBox">Bounding box of the field value, if
        /// appropriate.</param>
        /// <param name="confidence">Confidence score.</param>
        /// <param name="elements">When includeTextDetails is set to true, a
        /// list of references to the text elements constituting this
        /// field.</param>
        /// <param name="page">The 1-based page number in the input
        /// document.</param>

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets type of field value. Possible values include:
        /// 'string', 'date', 'time', 'phoneNumber', 'number', 'integer',
        /// 'array', 'object'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public FieldValueType Type { get; set; }

        /// <summary>
        /// Gets or sets string value.
        /// </summary>
        [JsonProperty(PropertyName = "valueString")]
        public string ValueString { get; set; }
        public bool ShouldSerializeValueString()
        {
            return (Type == FieldValueType.String);
        }


        /// <summary>
        /// Gets or sets date value.
        /// </summary>
        [JsonProperty(PropertyName = "valueDate")]
        public string ValueDate { get; set; }
        public bool ShouldSerializeValueDate()
        {
            return (Type == FieldValueType.Date);
        }

        /// <summary>
        /// Gets or sets time value.
        /// </summary>
        [JsonProperty(PropertyName = "valueTime")]
        public string ValueTime { get; set; }
        public bool ShouldSerializeValueTime()
        {
            return (Type == FieldValueType.Time);
        }

        /// <summary>
        /// Gets or sets phone number value.
        /// </summary>
        [JsonProperty(PropertyName = "valuePhoneNumber")]
        public string ValuePhoneNumber { get; set; }
        public bool ShouldSerializeValuePhoneNumber()
        {
            return (Type == FieldValueType.PhoneNumber);
        }

        /// <summary>
        /// Gets or sets floating point value.
        /// </summary>
        [JsonProperty(PropertyName = "valueNumber")]
        public double ValueNumber { get; set; }
        public bool ShouldSerializeValueNumber()
        {
            return (Type == FieldValueType.Number);
        }

        /// <summary>
        /// Gets or sets integer value.
        /// </summary>
        [JsonProperty(PropertyName = "valueInteger")]
        public int ValueInteger { get; set; }
        public bool ShouldSerializeValueInteger()
        {
            return (Type == FieldValueType.Integer);
        }

        /// <summary>
        /// Gets or sets array of field values.
        /// </summary>
        [JsonProperty(PropertyName = "valueArray")]
        public IList<FieldValue> ValueArray { get; set; }
        public bool ShouldSerializeValueArray()
        {
            return (Type == FieldValueType.Array);
        }

        /// <summary>
        /// Gets or sets dictionary of named field values.
        /// </summary>
        [JsonProperty(PropertyName = "valueObject")]
        public IDictionary<string, FieldValue> ValueObject { get; set; }
        public bool ShouldSerializeValueObject()
        {
            return (Type == FieldValueType.Object);
        }

        /// <summary>
        /// Gets or sets text content of the extracted field.
        /// </summary>
        [JsonProperty(PropertyName = "text")]
        public string Text { get; set; }
        public bool ShouldSerializeText()
        {
            return (Text != null);
        }

        /// <summary>
        /// Gets or sets bounding box of the field value, if appropriate.
        /// </summary>
        [JsonProperty(PropertyName = "boundingBox")]
        public BoundingBox BoundingBoxes { get; set; }
        public bool ShouldSerializeBoundingBoxes()
        {
            return (BoundingBoxes != null);
        }

        /// <summary>
        /// Gets or sets confidence score.
        /// </summary>
        [JsonProperty(PropertyName = "confidence")]
        public double? Confidence { get; set; }
        public bool ShouldSerializeConfidence()
        {
            return (Confidence != null);
        }


        /// <summary>
        /// Gets or sets when includeTextDetails is set to true, a list of
        /// references to the text elements constituting this field.
        /// </summary>
        [JsonProperty(PropertyName = "elements")]
        public IList<ElementReference> Elements { get; set; }
        public bool ShouldSerializeElements()
        {
            return (Elements != null);
        }

        /// <summary>
        /// Gets or sets the 1-based page number in the input document.
        /// </summary>
        [JsonProperty(PropertyName = "pageNumber")]
        public int Page { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ValueArray != null)
            {
                foreach (var element in ValueArray)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
            if (ValueObject != null)
            {
                foreach (var valueElement in ValueObject.Values)
                {
                    if (valueElement != null)
                    {
                        valueElement.Validate();
                    }
                }
            }
            if (Page < 1)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "Page", 1);
            }
        }
    }
}
